name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: windows-latest
    steps:
      - name: Print greeting
        run: Write-Host "Hello World!"
      - name: Print goodbye
        run: Write-Host "Done - bye!"
